server:
  port: 9776

spring:
  datasource:
    url: jdbc:h2:./db/Job_Search;AUTO_SERVER=true
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always