--liquibase formatted sql
--changeset Abu:add_employers_data
INSERT INTO USERS (name, surname, age, email, password, phone_number, avatar, ENABLED)
VALUES
    ('Peter', 'Wilson', 40, 'peter.wilson@example.com',
     '$2a$12$WB2YUbFcCN0tm44SBcKUjua9yiFBsfB3vW02IjuwzY7HGtlQIKzy2', '9876543210', 'avatar_peter.jpg', true),
    ('Sophie', 'Roberts', 35, 'sophie.roberts@example.com',
     '$2a$10$zLoPtjUjaZAcOPjEuFunnOS13swef0FFxo06ujuyobopYxwD5F/s2', '7654321987', 'avatar_sophie.jpg', true),
    ('David', 'Harris', 45, 'david.harris@example.com',
     '$2a$10$VGkwdmvXTqgn6yfmdZ6w7.NdMDeSYTs4JcDdySZ.yMdQ4qzGH3At.', '1122334455', 'avatar_david.jpg', true),
    ('Emma', 'Allen', 38, 'emma.allen@example.com',
     '$2a$10$UYXM0mgh1OLkf6r7Iq0kCe2KV/fZT/GB1SkbdddpjzXEHK8NOQomi', '763547234', 'avatar_emma.jpg', true),
    ('Tom', 'Carter', 42, 'tom.carter@example.com',
     '$2a$12$WB2YUbFcCN0tm44SBcKUjua9yiFBsfB3vW02IjuwzY7HGtlQIKzy2', '9988776655', 'avatar_tom.jpg', true),
    ('Olivia', 'King', 37, 'olivia.king@example.com',
     '$2a$10$zLoPtjUjaZAcOPjEuFunnOS13swef0FFxo06ujuyobopYxwD5F/s2', '1234432156', 'avatar_olivia.jpg', true),
    ('Jack', 'Scott', 39, 'jack.scott@example.com',
     '$2a$10$VGkwdmvXTqgn6yfmdZ6w7.NdMDeSYTs4JcDdySZ.yMdQ4qzGH3At.', '9876543210', 'avatar_jack.jpg', true),
    ('Lucy', 'Turner', 36, 'lucy.turner@example.com',
     '$2a$12$WB2YUbFcCN0tm44SBcKUjua9yiFBsfB3vW02IjuwzY7HGtlQIKzy2', '7654321987', 'avatar_lucy.jpg', true),
    ('Ben', 'Miller', 41, 'ben.miller@example.com',
     '$2a$10$zLoPtjUjaZAcOPjEuFunnOS13swef0FFxo06ujuyobopYxwD5F/s2', '9988776655', 'avatar_ben.jpg', true),
    ('Natalie', 'Moore', 37, 'natalie.moore@example.com',
     '$2a$10$VGkwdmvXTqgn6yfmdZ6w7.NdMDeSYTs4JcDdySZ.yMdQ4qzGH3At.', '1234432156', 'avatar_natalie.jpg', true),
    ('Mark', 'Clark', 43, 'mark.clark@example.com',
     '$2a$12$WB2YUbFcCN0tm44SBcKUjua9yiFBsfB3vW02IjuwzY7HGtlQIKzy2', '9876543210', 'avatar_mark.jpg', true),
    ('Laura', 'Young', 39, 'laura.young@example.com',
     '$2a$10$zLoPtjUjaZAcOPjEuFunnOS13swef0FFxo06ujuyobopYxwD5F/s2', '7654321987', 'avatar_laura.jpg', true),
    ('Chris', 'Hill', 44, 'chris.hill@example.com',
     '$2a$10$VGkwdmvXTqgn6yfmdZ6w7.NdMDeSYTs4JcDdySZ.yMdQ4qzGH3At.', '1122334455', 'avatar_chris.jpg', true),
    ('Rachel', 'Wright', 38, 'rachel.wright@example.com',
     '$2a$12$WB2YUbFcCN0tm44SBcKUjua9yiFBsfB3vW02IjuwzY7HGtlQIKzy2', '9988776655', 'avatar_rachel.jpg', true),
    ('Kevin', 'Adams', 40, 'kevin.adams@example.com',
     '$2a$10$zLoPtjUjaZAcOPjEuFunnOS13swef0FFxo06ujuyobopYxwD5F/s2', '1234432156', 'avatar_kevin.jpg', true);

INSERT INTO USER_AUTHORITY(user_id, authority_id)
VALUES
    ((SELECT id FROM USERS WHERE EMAIL = 'peter.wilson@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'sophie.roberts@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'david.harris@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'emma.allen@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'tom.carter@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'olivia.king@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'jack.scott@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'lucy.turner@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'ben.miller@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'natalie.moore@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'mark.clark@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'laura.young@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'chris.hill@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'rachel.wright@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'kevin.adams@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer'));

INSERT INTO categories (name)
VALUES ('Engineering'),
       ('Sales'),
       ('Human Resources'),
       ('Customer Support'),
       ('Operations'),
       ('Design'),
       ('Healthcare'),
       ('Education'),
       ('Legal'),
       ('Hospitality'),
       ('Construction'),
       ('Research');

INSERT INTO vacancies (name, description, category_id, salary, exp_from, exp_to, is_active, author_id, created_date, update_date)
VALUES
    ('Software Developer', 'Description for software developer position',
     (SELECT id FROM categories WHERE name = 'Software Development'),
     80000, 3, 5, 1,
     (SELECT id FROM USERS WHERE name = 'Michael' AND surname = 'Johnson'),
     NOW(), NOW()),

    ('Marketing Manager', 'Description for marketing manager position',
     (SELECT id FROM categories WHERE name = 'Marketing'),
     70000, 5, 7, 1,
     (SELECT id FROM USERS WHERE name = 'Jane' AND surname = 'Smith'),
     NOW(), NOW()),

    ('Financial Analyst', 'Description for financial analyst position',
     (SELECT id FROM categories WHERE name = 'Finance'),
     75000, 3, 6, 1,
     (SELECT id FROM USERS WHERE name = 'David' AND surname = 'Harris'),
     NOW(), NOW()),

    ('Sales Executive', 'Description for sales executive position',
     (SELECT id FROM categories WHERE name = 'Sales'),
     70000, 2, 4, 1,
     (SELECT id FROM USERS WHERE name = 'Sophie' AND surname = 'Roberts'),
     NOW(), NOW()),

    ('HR Manager', 'Description for HR manager position',
     (SELECT id FROM categories WHERE name = 'Human Resources'),
     80000, 5, 8, 1,
     (SELECT id FROM USERS WHERE name = 'Emma' AND surname = 'Allen'),
     NOW(), NOW()),

    ('Customer Support Specialist', 'Description for customer support specialist position',
     (SELECT id FROM categories WHERE name = 'Customer Support'),
     60000, 1, 3, 1,
     (SELECT id FROM USERS WHERE name = 'Tom' AND surname = 'Carter'),
     NOW(), NOW()),

    ('Operations Manager', 'Description for operations manager position',
     (SELECT id FROM categories WHERE name = 'Operations'),
     85000, 6, 8, 1,
     (SELECT id FROM USERS WHERE name = 'Olivia' AND surname = 'King'),
     NOW(), NOW()),

    ('UX/UI Designer', 'Description for UX/UI designer position',
     (SELECT id FROM categories WHERE name = 'Design'),
     75000, 3, 5, 1,
     (SELECT id FROM USERS WHERE name = 'Jack' AND surname = 'Scott'),
     NOW(), NOW()),

    ('Nurse', 'Description for nurse position',
     (SELECT id FROM categories WHERE name = 'Healthcare'),
     70000, 2, 5, 1,
     (SELECT id FROM USERS WHERE name = 'Lucy' AND surname = 'Turner'),
     NOW(), NOW()),

    ('Math Teacher', 'Description for math teacher position',
     (SELECT id FROM categories WHERE name = 'Education'),
     65000, 4, 6, 1,
     (SELECT id FROM USERS WHERE name = 'Ben' AND surname = 'Miller'),
     NOW(), NOW()),

    ('Legal Counsel', 'Description for legal counsel position',
     (SELECT id FROM categories WHERE name = 'Legal'),
     90000, 7, 10, 1,
     (SELECT id FROM USERS WHERE name = 'Natalie' AND surname = 'Moore'),
     NOW(), NOW()),

    ('Hotel Manager', 'Description for hotel manager position',
     (SELECT id FROM categories WHERE name = 'Hospitality'),
     80000, 5, 8, 1,
     (SELECT id FROM USERS WHERE name = 'Mark' AND surname = 'Clark'),
     NOW(), NOW()),

    ('Construction Engineer', 'Description for construction engineer position',
     (SELECT id FROM categories WHERE name = 'Construction'),
     85000, 6, 9, 1,
     (SELECT id FROM USERS WHERE name = 'Laura' AND surname = 'Young'),
     NOW(), NOW()),

    ('Research Scientist', 'Description for research scientist position',
     (SELECT id FROM categories WHERE name = 'Research'),
     95000, 8, 12, 1,
     (SELECT id FROM USERS WHERE name = 'Chris' AND surname = 'Hill'),
     NOW(), NOW()),

    ('Event Coordinator', 'Description for event coordinator position',
     (SELECT id FROM categories WHERE name = 'Hospitality'),
     70000, 2, 4, 1,
     (SELECT id FROM USERS WHERE name = 'Rachel' AND surname = 'Wright'),
     NOW(), NOW()),

    ('Civil Rights Attorney', 'Description for civil rights attorney position',
     (SELECT id FROM categories WHERE name = 'Legal'),
     100000, 8, 12, 1,
     (SELECT id FROM USERS WHERE name = 'Kevin' AND surname = 'Adams'),
     NOW(), NOW());
