--liquibase formatted sql
--changeset Abu:add_employers_data
INSERT INTO USERS (name, surname, age, email, password, phone_number, avatar, ENABLED)
VALUES
    ('Peter', 'Wilson', 40, 'peter.wilson@example.com',
     '$2a$12$WB2YUbFcCN0tm44SBcKUjua9yiFBsfB3vW02IjuwzY7HGtlQIKzy2', '9876543210', 'avatar_peter.jpg', true),
    ('Sophie', 'Roberts', 35, 'sophie.roberts@example.com',
     '$2a$10$zLoPtjUjaZAcOPjEuFunnOS13swef0FFxo06ujuyobopYxwD5F/s2', '7654321987', 'avatar_sophie.jpg', true),
    ('David', 'Harris', 45, 'david.harris@example.com',
     '$2a$10$VGkwdmvXTqgn6yfmdZ6w7.NdMDeSYTs4JcDdySZ.yMdQ4qzGH3At.', '1122334455', 'avatar_david.jpg', true),
    ('Emma', 'Allen', 38, 'emma.allen@example.com',
     '$2a$10$UYXM0mgh1OLkf6r7Iq0kCe2KV/fZT/GB1SkbdddpjzXEHK8NOQomi', '763547234', 'avatar_emma.jpg', true),
    ('Tom', 'Carter', 42, 'tom.carter@example.com',
     '$2a$12$WB2YUbFcCN0tm44SBcKUjua9yiFBsfB3vW02IjuwzY7HGtlQIKzy2', '9988776655', 'avatar_tom.jpg', true),
    ('Olivia', 'King', 37, 'olivia.king@example.com',
     '$2a$10$zLoPtjUjaZAcOPjEuFunnOS13swef0FFxo06ujuyobopYxwD5F/s2', '1234432156', 'avatar_olivia.jpg', true),
    ('Jack', 'Scott', 39, 'jack.scott@example.com',
     '$2a$10$VGkwdmvXTqgn6yfmdZ6w7.NdMDeSYTs4JcDdySZ.yMdQ4qzGH3At.', '9876543210', 'avatar_jack.jpg', true),
    ('Lucy', 'Turner', 36, 'lucy.turner@example.com',
     '$2a$12$WB2YUbFcCN0tm44SBcKUjua9yiFBsfB3vW02IjuwzY7HGtlQIKzy2', '7654321987', 'avatar_lucy.jpg', true),
    ('Ben', 'Miller', 41, 'ben.miller@example.com',
     '$2a$10$zLoPtjUjaZAcOPjEuFunnOS13swef0FFxo06ujuyobopYxwD5F/s2', '9988776655', 'avatar_ben.jpg', true),
    ('Natalie', 'Moore', 37, 'natalie.moore@example.com',
     '$2a$10$VGkwdmvXTqgn6yfmdZ6w7.NdMDeSYTs4JcDdySZ.yMdQ4qzGH3At.', '1234432156', 'avatar_natalie.jpg', true),
    ('Mark', 'Clark', 43, 'mark.clark@example.com',
     '$2a$12$WB2YUbFcCN0tm44SBcKUjua9yiFBsfB3vW02IjuwzY7HGtlQIKzy2', '9876543210', 'avatar_mark.jpg', true),
    ('Laura', 'Young', 39, 'laura.young@example.com',
     '$2a$10$zLoPtjUjaZAcOPjEuFunnOS13swef0FFxo06ujuyobopYxwD5F/s2', '7654321987', 'avatar_laura.jpg', true),
    ('Chris', 'Hill', 44, 'chris.hill@example.com',
     '$2a$10$VGkwdmvXTqgn6yfmdZ6w7.NdMDeSYTs4JcDdySZ.yMdQ4qzGH3At.', '1122334455', 'avatar_chris.jpg', true),
    ('Rachel', 'Wright', 38, 'rachel.wright@example.com',
     '$2a$12$WB2YUbFcCN0tm44SBcKUjua9yiFBsfB3vW02IjuwzY7HGtlQIKzy2', '9988776655', 'avatar_rachel.jpg', true),
    ('Kevin', 'Adams', 40, 'kevin.adams@example.com',
     '$2a$10$zLoPtjUjaZAcOPjEuFunnOS13swef0FFxo06ujuyobopYxwD5F/s2', '1234432156', 'avatar_kevin.jpg', true);

INSERT INTO USER_AUTHORITY(user_id, authority_id)
VALUES
    ((SELECT id FROM USERS WHERE EMAIL = 'peter.wilson@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'sophie.roberts@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'david.harris@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'emma.allen@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'tom.carter@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'olivia.king@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'jack.scott@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'lucy.turner@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'ben.miller@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'natalie.moore@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'mark.clark@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'laura.young@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'chris.hill@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'rachel.wright@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer')),
    ((SELECT id FROM USERS WHERE EMAIL = 'kevin.adams@example.com'),
     (SELECT id FROM AUTHORITIES WHERE ROLE = 'employer'));

INSERT INTO categories (name)
VALUES ('Engineering'),
       ('Sales'),
       ('Human Resources'),
       ('Customer Support'),
       ('Operations'),
       ('Design'),
       ('Healthcare'),
       ('Education'),
       ('Legal'),
       ('Hospitality'),
       ('Construction'),
       ('Research');